[package]
name = "planebotcli-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
autobins = false

[[bin]]
name = "planebotcli"
path = "src/main.rs"

[[bin]]
name = "pbot"
path = "src/bin/pbot.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
planebotcli-cache = { path = "../planebotcli-cache" }
planebotcli-client = { path = "../planebotcli-client" }
planebotcli-core = { path = "../planebotcli-core" }
planebotcli-format = { path = "../planebotcli-format" }
planebotcli-html = { path = "../planebotcli-html" }
planebotcli-resolve = { path = "../planebotcli-resolve" }
planebotcli-types = { path = "../planebotcli-types" }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
mockito = "1"
