[package]
name = "planebotcli-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
planebotcli-cache = { path = "../planebotcli-cache" }
planebotcli-core = { path = "../planebotcli-core" }
planebotcli-types = { path = "../planebotcli-types" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
